use std::ffi::OsStr;
use std::fs;
use std::path::Path;

use walkdir::WalkDir;

use crate::detection::finding::{Finding, FindingCategory, LineRange, Severity};
use crate::domain::errors::PapertowelError;

pub const DETECTOR_NAME: &str = "maintenance";

const CODE_EXTENSIONS: [&str; 8] = ["rs", "go", "py", "ts", "tsx", "js", "cs", "zig"];
const DOC_EXTENSIONS: [&str; 4] = ["md", "rst", "txt", "adoc"];
const CONFIG_EXTENSIONS: [&str; 4] = ["toml", "yaml", "yml", "json"];
const PLACEHOLDER_MARKERS: [&str; 8] = [
    "coming soon",
    "todo",
    "tbd",
    "placeholder",
    "lorem ipsum",
    "to be added",
    "wip",
    "generated by",
];

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MaintenanceDetectionConfig {
    pub max_code_files_for_hollow_repo: usize,
    pub min_non_code_files: usize,
    pub min_placeholder_hits: usize,
    pub min_doc_to_code_ratio: f32,
}

impl Default for MaintenanceDetectionConfig {
    fn default() -> Self {
        Self {
            max_code_files_for_hollow_repo: 3,
            min_non_code_files: 5,
            min_placeholder_hits: 2,
            min_doc_to_code_ratio: 1.2,
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq)]
struct MaintenanceMetrics {
    code_files: usize,
    doc_files: usize,
    config_files: usize,
    placeholder_hits: usize,
    has_tests_dir: bool,
}

pub fn detect_repo(repo_root: impl AsRef<Path>) -> Result<Vec<Finding>, PapertowelError> {
    detect_repo_with_config(repo_root, MaintenanceDetectionConfig::default())
}

pub fn detect_repo_with_config(
    repo_root: impl AsRef<Path>,
    config: MaintenanceDetectionConfig,
) -> Result<Vec<Finding>, PapertowelError> {
    let repo_root = repo_root.as_ref();
    let metrics = scan_repo(repo_root)?;

    let non_code_files = metrics.doc_files + metrics.config_files;
    let doc_to_code_ratio = if metrics.code_files == 0 {
        metrics.doc_files as f32
    } else {
        metrics.doc_files as f32 / metrics.code_files as f32
    };

    let hollow_repo = metrics.code_files <= config.max_code_files_for_hollow_repo
        && non_code_files >= config.min_non_code_files
        && metrics.placeholder_hits >= config.min_placeholder_hits
        && doc_to_code_ratio >= config.min_doc_to_code_ratio
        && !metrics.has_tests_dir;

    if !hollow_repo {
        return Ok(Vec::new());
    }

    let severity = if metrics.code_files <= 1 && metrics.placeholder_hits >= 3 {
        Severity::High
    } else {
        Severity::Medium
    };
    let confidence = ((non_code_files as f32 / 8.0) * 0.5
        + (metrics.placeholder_hits as f32 / 6.0) * 0.3
        + doc_to_code_ratio.min(3.0) / 3.0 * 0.2)
        .min(1.0);

    let mut finding = Finding::new(
        "maintenance.hollow_repo",
        FindingCategory::Maintenance,
        severity,
        confidence,
        repo_root.join("."),
        format!(
            "Repository appears maintenance-light (code files: {}, docs: {}, config: {}, placeholder hits: {}).",
            metrics.code_files, metrics.doc_files, metrics.config_files, metrics.placeholder_hits
        ),
    )?;
    finding.line_range = Some(LineRange::new(1, 1)?);
    finding.suggestion = Some(
		"Prioritize substantive code/test evolution and prune generated placeholder docs that overstate project maturity."
			.to_owned(),
	);

    Ok(vec![finding])
}

fn scan_repo(repo_root: &Path) -> Result<MaintenanceMetrics, PapertowelError> {
    let mut metrics = MaintenanceMetrics::default();

    for entry in WalkDir::new(repo_root) {
        let entry = entry.map_err(|error| {
            let io_error = std::io::Error::other(error.to_string());
            let path = error
                .path()
                .map_or_else(|| repo_root.to_path_buf(), Path::to_path_buf);
            PapertowelError::io_with_path(path, io_error)
        })?;

        let path = entry.path();
        if path.components().any(|part| {
            part.as_os_str() == OsStr::new(".git")
                || part.as_os_str() == OsStr::new("target")
                || part.as_os_str() == OsStr::new(".coraline")
        }) {
            continue;
        }

        if path.is_dir() {
            if path.ends_with("tests") {
                metrics.has_tests_dir = true;
            }
            continue;
        }

        let Some(ext) = path.extension().and_then(OsStr::to_str) else {
            continue;
        };

        if CODE_EXTENSIONS.contains(&ext) {
            metrics.code_files += 1;
        } else if DOC_EXTENSIONS.contains(&ext) {
            metrics.doc_files += 1;
            metrics.placeholder_hits += count_placeholder_hits(path)?;
        } else if CONFIG_EXTENSIONS.contains(&ext) {
            metrics.config_files += 1;
        }
    }

    Ok(metrics)
}

fn count_placeholder_hits(path: &Path) -> Result<usize, PapertowelError> {
    let content =
        fs::read_to_string(path).map_err(|error| PapertowelError::io_with_path(path, error))?;
    let lowered = content.to_ascii_lowercase();
    Ok(PLACEHOLDER_MARKERS
        .iter()
        .filter(|marker| lowered.contains(**marker))
        .count())
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::TempDir;

    use crate::scrubber::maintenance::{
        DETECTOR_NAME, MaintenanceDetectionConfig, detect_repo_with_config,
    };

    #[test]
    fn detector_name_is_stable() {
        assert_eq!(DETECTOR_NAME, "maintenance");
    }

    #[test]
    fn maintenance_detector_ignores_active_repo_shape() {
        let temp = TempDir::new();
        assert!(temp.is_ok());
        let temp = match temp {
            Ok(temp) => temp,
            Err(error) => panic!("failed to create tempdir: {error}"),
        };

        let src = temp.path().join("src");
        let tests = temp.path().join("tests");
        let mk_src = fs::create_dir_all(&src);
        let mk_tests = fs::create_dir_all(&tests);
        assert!(mk_src.is_ok());
        assert!(mk_tests.is_ok());
        assert!(fs::write(src.join("lib.rs"), "pub fn a() {}\n").is_ok());
        assert!(fs::write(src.join("mod.rs"), "pub fn b() {}\n").is_ok());
        assert!(
            fs::write(
                tests.join("integration.rs"),
                "#[test] fn ok() { assert!(true); }\n"
            )
            .is_ok()
        );
        assert!(fs::write(temp.path().join("README.md"), "Project docs\n").is_ok());

        let findings = detect_repo_with_config(temp.path(), MaintenanceDetectionConfig::default());
        assert!(findings.is_ok());
        let findings = match findings {
            Ok(findings) => findings,
            Err(error) => panic!("unexpected maintenance detector error: {error}"),
        };
        assert!(findings.is_empty());
    }

    #[test]
    fn maintenance_detector_flags_hollow_repo_shape() {
        let temp = TempDir::new();
        assert!(temp.is_ok());
        let temp = match temp {
            Ok(temp) => temp,
            Err(error) => panic!("failed to create tempdir: {error}"),
        };

        let src = temp.path().join("src");
        assert!(fs::create_dir_all(&src).is_ok());
        assert!(fs::write(src.join("main.rs"), "fn main() {}\n").is_ok());

        let docs = [
            ("README.md", "Coming soon. Generated by template."),
            ("CONTRIBUTING.md", "To be added soon."),
            ("SECURITY.md", "TBD placeholder."),
            ("ROADMAP.md", "WIP and lorem ipsum."),
        ];
        for (name, content) in docs {
            assert!(fs::write(temp.path().join(name), content).is_ok());
        }
        assert!(fs::write(temp.path().join("config.toml"), "mode = \"demo\"\n").is_ok());

        let findings = detect_repo_with_config(temp.path(), MaintenanceDetectionConfig::default());
        assert!(findings.is_ok());
        let findings = match findings {
            Ok(findings) => findings,
            Err(error) => panic!("unexpected maintenance detector error: {error}"),
        };

        assert_eq!(findings.len(), 1);
    }
}
